//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountInfo
    {
        public string ACCOUNT_ID { get; set; }
        public string USER_NAME { get; set; }
        public string ACCOUNT_CCCD { get; set; }
        public Nullable<System.DateTime> ACCOUNT_BIRTHDAY { get; set; }
        public Nullable<bool> ACCOUNT_GENDER { get; set; }
        public Nullable<double> ACCOUNT_HEIGHT { get; set; }
        public Nullable<double> ACCOUNT_WEIGHT { get; set; }
        public string ACCOUNT_PHONE { get; set; }
        public string ACCOUNT_EMAIL { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
