//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL3.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PBL3Entities1 : DbContext
    {
        public PBL3Entities1()
            : base("name=PBL3Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<AccountInfo> AccountInfoes { get; set; }
        public virtual DbSet<BienLai> BienLais { get; set; }
        public virtual DbSet<LoaiGoi> LoaiGois { get; set; }
        public virtual DbSet<Lop> Lops { get; set; }
        public virtual DbSet<PhienTap> PhienTaps { get; set; }
        public virtual DbSet<QuanLyLop> QuanLyLops { get; set; }
        public virtual DbSet<QuanLyThietBi> QuanLyThietBis { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<ThietBi> ThietBis { get; set; }
    }
}
