

CREATE TABLE Account(
	ACCOUNT_ID nchar(5) NOT NULL primary key,
	ACCOUNT_NAME varchar(20),
	ACCOUNT_PASSWORD varchar(20),
	ACCOUNT_ROLE int
);


/* DO DAI CO DINH : NCHAR (UNI)
TUY BIEN: VARCHAR
NVARCHAR( TUY BIEN, UNI)
*/
CREATE TABLE AccountInfo(
	ACCOUNT_ID nchar(5) NOT NULL primary key,
	FOREIGN KEY (ACCOUNT_ID) REFERENCES Account (ACCOUNT_ID),
	USER_NAME nvarchar(28),
	ACCOUNT_CCCD NCHAR(20),
	/*H/D/M/Y*/
	ACCOUNT_BIRTHDAY DATETIME,
	ACCOUNT_GENDER BIT,
	ACCOUNT_HEIGHT FLOAT,
	ACCOUNT_WEIGHT FLOAT,
	ACCOUNT_PHONE NCHAR(10),
	ACCOUNT_EMAIL VARCHAR(28)

);


CREATE TABLE ThietBi(
	THIETBI_ID  NCHAR(5) NOT NULL PRIMARY KEY,
	THIETBI_NAME NVARCHAR(25),
	THIETBI_STATUS INT,
	THIETBI_NUM INT
);

CREATE TABLE QuanLyThietBi(
	QUANLYTHIETBI_ID NCHAR(5) NOT NULL PRIMARY KEY,
	ACCOUNT_ID nchar(5),
	THIETBI_ID  NCHAR(5),
	FOREIGN KEY (ACCOUNT_ID) REFERENCES Account (ACCOUNT_ID),
	FOREIGN KEY (THIETBI_ID) REFERENCES ThietBi (THIETBI_ID)
);

CREATE TABLE LoaiGoi(
	GOI_ID NCHAR(5) NOT NULL PRIMARY KEY,
	GOI_NUMBERSESSION INT
);
 CREATE TABLE PhienTap(
	PHIENTAP_ID NCHAR(5) NOT NULL PRIMARY KEY,
	PHIENTAP_DAY DATE,
	PHIENTAP_START INT,
	PHIENTAP_END INT
 );

 CREATE TABLE Lop(
	LOP_ID NCHAR(5) NOT NULL PRIMARY KEY,
	LOP_STAFFID NCHAR(5),
	LOP_CUSTOMERID NCHAR(5),
	PHIENTAP_ID NCHAR(5),
	GOI_ID NCHAR(5),
	LOP_START DATETIME,
	LOP_END DATETIME,

	FOREIGN KEY (GOI_ID) REFERENCES LoaiGoi (GOI_ID),
	FOREIGN KEY (PHIENTAP_ID) REFERENCES PhienTap (PHIENTAP_ID),
 );

 CREATE TABLE QuanLyLop(
	QUANLYLOP_ID  NCHAR(5) NOT NULL PRIMARY KEY,
	ACCOUNT_ID NCHAR(5),
	LOP_ID NCHAR(5),

	FOREIGN KEY (LOP_ID) REFERENCES Lop (LOP_ID),
	FOREIGN KEY (ACCOUNT_ID) REFERENCES Account (ACCOUNT_ID),

 );

 CREATE TABLE BienLai(
	BIENLAI_ID NCHAR(5) NOT NULL PRIMARY KEY,
	BIENLAI_PAYMENT INT,
	LOP_ID NCHAR(5),
	ACCOUNT_ID NCHAR(5),
	BIENLAI_START DATETIME,
	BIENLAI_END DATETIME,
	FOREIGN KEY (LOP_ID) REFERENCES Lop (LOP_ID),
	FOREIGN KEY (ACCOUNT_ID) REFERENCES Account (ACCOUNT_ID)

 );

